name: pocket_open_access
description: Flutter mobile app to manage Open Access resources. Uses the Core
  API to search for OA articles and journals.

publish_to: 'none'

version: 1.1.5+8

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_smart_retry: ^1.2.0
  equatable: ^2.0.3
  file: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  platform: ^3.0.2
  syncfusion_flutter_pdfviewer: ^20.1.47-beta
  syncfusion_pdfviewer_web: ^20.1.47-beta.1
  url_launcher: ^6.0.15

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  http_mock_adapter: ^0.3.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.1
  mockingjay: ^0.3.0
  mocktail: ^0.3.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/launch_icon/ios/pocket-open-access-logo-ios.png"
  image_path_android: "assets/images/launch_icon/android/pocket-open-access-logo-android.png"
  adaptive_icon_background: "#e5e5e5"
  adaptive_icon_foreground: "assets/images/launch_icon/android/pocket-open-access-logo-android.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - test.pdf
    - assets/images/
    - assets/config/app-config.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: FingerPaint
      fonts:
        - asset: assets/fonts/FingerPaint-Regular.ttf
